import SwiftUI
import GituniaCore

/// Explains and edits what tags actually do: free-form labels on a repository that the sidebar's
/// top picker can filter down to. Replaces a bare `.alert` that gave no hint what it was for.
struct TagEditorSheet: View {
    let store: RepositoryStore
    let workspace: WorkspaceStore
    @Environment(\.dismiss) private var dismiss

    @State private var currentTags: Set<String>
    @State private var newTagText = ""
    @State private var localAIOnly: Bool
    @State private var customAgents: Bool
    @State private var agentPatternsText: String
    @State private var fetchCadence: FetchCadence
    @State private var secretScanIgnored: [String]

    init(store: RepositoryStore, workspace: WorkspaceStore) {
        self.store = store
        self.workspace = workspace
        _currentTags = State(initialValue: store.repo.tags)
        _localAIOnly = State(initialValue: store.repo.localAIOnly)
        _customAgents = State(initialValue: store.agentPatterns != nil)
        _agentPatternsText = State(initialValue: store.agentProfile.patterns.joined(separator: "\n"))
        _fetchCadence = State(initialValue: store.fetchCadence)
        _secretScanIgnored = State(initialValue: store.secretScanIgnoredPaths.sorted())
    }

    /// Every tag worth showing as a chip: this repo's own tags plus every tag used anywhere in
    /// the workspace, so reusing an existing tag is one click instead of retyping it exactly.
    private var tagOptions: [String] {
        Set(workspace.allTags).union(currentTags).sorted()
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("Tags — \(store.repo.name)")
                .font(.title3.bold())

            Text("Tags label a repository so the sidebar's filter can narrow the list down to just the ones you want. A repository can carry as many as you like.")
                .font(.callout)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)

            if tagOptions.isEmpty {
                Text("No tags yet.").font(.callout).foregroundStyle(.secondary)
            } else {
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack(spacing: 6) {
                        ForEach(tagOptions, id: \.self) { tag in
                            tagChip(tag)
                        }
                    }
                }
            }

            HStack {
                TextField("New tag (or several, comma-separated)", text: $newTagText)
                    .onSubmit(addTypedTags)
                Button("Add", action: addTypedTags)
                    .disabled(newTagText.trimmingCharacters(in: .whitespaces).isEmpty)
            }

            Divider()

            Toggle(isOn: $localAIOnly) {
                VStack(alignment: .leading, spacing: 2) {
                    Text("Local AI only")
                    Text("Commit messages for this repository are only ever generated by a local model; cloud AI providers are never used.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            Toggle("Use custom agent patterns for this repository", isOn: $customAgents)
            if customAgents {
                VStack(alignment: .leading, spacing: 4) {
                    TextField("One pattern per line", text: $agentPatternsText, axis: .vertical)
                        .lineLimit(3...6)
                        .font(.callout.monospaced())
                    Text("Overrides the global list in Settings → Agents.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            VStack(alignment: .leading, spacing: 4) {
                Picker("Auto-fetch", selection: $fetchCadence) {
                    Text("Paused").tag(FetchCadence.paused)
                    Text("Normal").tag(FetchCadence.normal)
                    Text("Intensive").tag(FetchCadence.intensive)
                }
                Text("Intensive fetches five times as often as the interval in Settings — for repositories agents are pushing to right now.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }

            if !secretScanIgnored.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Not scanned for secrets")
                    VStack(alignment: .leading, spacing: 2) {
                        ForEach(secretScanIgnored, id: \.self) { path in
                            HStack {
                                Text(path).font(.callout.monospaced()).lineLimit(1).truncationMode(.head)
                                Spacer()
                                Button { secretScanIgnored.removeAll { $0 == path } } label: {
                                    Image(systemName: "minus.circle")
                                }
                                .buttonStyle(.borderless)
                                .help("Scan this file for secrets again")
                            }
                        }
                    }
                    Text("Excluded from Gitunia's secret checks (push, commit, AI) via \"Don't Check Selected Again\".")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }

            HStack {
                Spacer()
                Button("Cancel", role: .cancel) { dismiss() }
                    .keyboardShortcut(.cancelAction)
                Button("Save") {
                    workspace.setTags(currentTags, for: store)
                    workspace.setLocalAIOnly(localAIOnly, for: store)
                    let patterns = agentPatternsText.split(separator: "\n").map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
                    workspace.setAgentPatterns(customAgents ? patterns : nil, for: store)
                    workspace.setFetchCadence(fetchCadence, for: store)
                    if secretScanIgnored != store.secretScanIgnoredPaths.sorted() {
                        workspace.setSecretScanIgnoredPaths(secretScanIgnored, for: store)
                    }
                    dismiss()
                }
                .keyboardShortcut(.defaultAction)
            }
        }
        .padding(20)
        .frame(width: 420)
    }

    private func tagChip(_ tag: String) -> some View {
        let selected = currentTags.contains(tag)
        return Button {
            if selected { currentTags.remove(tag) } else { currentTags.insert(tag) }
        } label: {
            HStack(spacing: 4) {
                if selected { Image(systemName: "checkmark").font(.caption2.bold()) }
                Text(tag)
            }
            .font(.callout)
            .padding(.horizontal, 10).padding(.vertical, 5)
            .background(selected ? Theme.brand : Color.secondary.opacity(0.15), in: Capsule())
            .foregroundStyle(selected ? Color.white : Color.primary)
        }
        .buttonStyle(.plain)
    }

    private func addTypedTags() {
        let parts = newTagText.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        guard !parts.isEmpty else { return }
        currentTags.formUnion(parts)
        newTagText = ""
    }
}
